import { useParams, Link } from "wouter";
import { useQuery } from "@tanstack/react-query";
import { format, parseISO } from "date-fns";
import { ru } from "date-fns/locale";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import type { ReceiptBooking } from "@shared/schema";
const methods: Record<string,string>={card:"Карта",sbp:"СБП"};
export default function Receipt(){const {bookingId}=useParams<{bookingId:string}>();const {data,error,isLoading}=useQuery<ReceiptBooking>({queryKey:["/api/receipts",bookingId],enabled:!!bookingId}); if(isLoading)return <div className="min-h-screen p-10">Загрузка...</div>; if(error)return <div className="min-h-screen flex items-center justify-center"><Card className="rounded-2xl"><CardContent className="p-8 text-center"><p className="text-muted-foreground">{(error as Error).message||"Квитанция доступна только после оплаты."}</p><Link href="/account"><Button className="mt-4">В кабинет</Button></Link></CardContent></Card></div>; if(!data)return null; const total=data.totalPrice+data.deposit; return <div className="min-h-screen py-10"><div className="mx-auto max-w-3xl px-6"><Card className="rounded-2xl print:border-0"><CardContent className="p-8 space-y-6"><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-primary">IMYA</p><h1 className="text-3xl font-bold">Квитанция об оплате</h1><p className="text-muted-foreground">Бронирование № {data.id}</p></div><Button onClick={()=>window.print()} className="print:hidden">Печать</Button></div><div className="grid sm:grid-cols-2 gap-3 text-sm">{[["Дата оформления",format(parseISO(data.createdAt),"d MMMM yyyy, HH:mm",{locale:ru})],["Клиент",data.user.name],["Email",data.user.email],["Товар",data.item.title],["Бренд",data.item.brand],["Даты аренды",`${format(parseISO(data.startDate),"d MMM",{locale:ru})} — ${format(parseISO(data.endDate),"d MMM yyyy",{locale:ru})}`],["Количество дней",String(data.days)],["Стоимость аренды",`${data.totalPrice.toLocaleString("ru-RU")} ₽`],["Залог",`${data.deposit.toLocaleString("ru-RU")} ₽`],["Итоговая сумма",`${total.toLocaleString("ru-RU")} ₽`],["Способ оплаты",methods[data.paymentMethod||""]||"—"],["Статус оплаты","Оплачено"],["Дата оплаты",data.paidAt?format(parseISO(data.paidAt),"d MMMM yyyy, HH:mm",{locale:ru}):"—"]].map(([k,v])=><div key={k} className="rounded-xl border p-3"><p className="text-muted-foreground">{k}</p><p className="font-medium">{v}</p></div>)}</div></CardContent></Card></div></div>}
